version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: virtufit-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: virtufit
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017" # اختياري لو تبي توصل من الكمبيوتر مباشرة
volumes:
  mongo-data:
